README.md, lib/tortoise.ex, test/test_helper.exs, test/tortoise_test.exs
This has two changes: 
1. Dialyzer caught the Application.start callback requiring `:normal` which it won't actually be sent. I updated the code to ignore the restart type field and where something was passed, I made it `:temporary` since that's the default.
2. Add a check on the argument type to `subscribe` to avoid a never ending recursion.
=> Application.start parameter update and subscribe argument

lib/tortoise/connection.ex, lib/tortoise/connection/controller.ex, lib/tortoise/connection/inflight.ex, lib/tortoise/connection/inflight/track.ex, lib/tortoise/driver.ex, lib/tortoise/driver/default.ex, lib/tortoise/driver/logger.ex, test/tortoise/connection/controller_test.exs, test/tortoise/connection_test.exs
The "Driver" allow the user to specify what should happen when certain events happen on the connection. The plan is to implement callbacks for events such as a connection state change, a subscription state change, and when the client receive a message on a topic filter it subscribe to. Callbacks such as init and terminating should also be available to the user.
When applied it should solve #4
=> Change the interface for the user defined driver behaviour

lib/tortoise/connection.ex, lib/tortoise/connection/receiver.ex
Sometimes the tests can get the application into weird states, and this causes weird output to appear in the test reports—not that they are failing any of the tests…things would just be much cleaner if it didn't output that stuff.
I will investigate the causes and take care of the reasons processes crashes. When this is applied it should fix #14
=> Fix output sometimes written during test runs

README.md, lib/tortoise.ex, lib/tortoise/connection.ex, lib/tortoise/connection/controller.ex, lib/tortoise/connection/inflight.ex, lib/tortoise/connection/transmitter.ex, lib/tortoise/connection/transmitter/pipe.ex, lib/tortoise/pipe.ex, test/tortoise/connection/controller_test.exs, test/tortoise/connection/transmitter_test.exs, test/tortoise/pipe_test.exs
This PR aims to revamp the user facing publish interface such that:
`Tortoise.publish/4`, where arguments are `client_id`, `topic`, `payload` (default: `nil`), and `opts` (default `[qos: 0]`)
`Tortoise.publish_sync/5`, where arguments are `client_id`, `topic`, `payload` (default: `nil`), `opts` (default `[qos: 0]`), and lastly a `timeout` (default `:infinity`)
The `publish_sync` form will block the caller until the message has been delivered—when sync publishing a QoS0 message that will be instantly. When using the non-sync form a message will get passed to the calling process, unless the QoS is 0—I will revamp the internal messages that communicate back to the calling process as well in this PR, so the returned message has the form `{{Tortoise, client_id}, ref, result}`.
Furthermore I …
=> Revamp the user facing publish interface

lib/tortoise.ex, lib/tortoise/connection.ex, lib/tortoise/connection/controller.ex, lib/tortoise/connection/inflight/track.ex, test/tortoise/connection/controller_test.exs, test/tortoise/connection_test.exs
Have the Connection process keep track of the subscription state so it can reconnect to the expected topics if it happens to reconnect with a clean state.
A list of topics are given at configuration time, but it is possible to subscribe (and unsubscribe) after the initialisation, so this aims to make it capable of reflecting the subscription changes in the subscription struct held in the connection process state.
When done and applied: Fixes #10
=> Track and reflect subscriptions and unsubscriptions in Tortoise.Connection

README.md, mix.exs, mix.lock
To build the documentation run the following in a terminal emulator:
``` shell
MIX_ENV=docs mix docs
```
This will build the documentation and place it in a folder called *doc* in the root of the project.
=> Add ex_doc and an ex_doc setup to the project

lib/tortoise/connection/controller.ex, lib/tortoise/handler/logger.ex, test/tortoise/connection/controller_test.exs
This pass the result of subscriptions that failed (was denied) or was accepted with a different QoS than the one requested. In these cases the `subscription/3` callback will get called on the user defined handler module, such that:
- `subscription({:error, reason = :access_deined}, topic_filter, state) -> …`
- `subscription({:warn, [requested: 2, accepted: 0]}, topic_filter, state) -> …`
This will allow the user to decide on what to do in these cases, and if no special action is taken it will crash the client with a reasonable function clause error message.
For now the only error reason handled in the error case is `:access_denied`. When we get support for MQTT 5 there will be more kinds of errors that can be returned.
When applied this should fix #27
=> Let the callback module decide what to do with failing subscriptions

.travis.yml, README.md, mix.exs, mix.lock
This will make the test coverage more visible; currently we are hovering around 88% test coverage, which is good, but could be better.
I should get a test coverage batch on the README, and have coverage run on the CI.
=> Add excoveralls and configuration to the project

CHANGELOG.md, README.md, lib/tortoise/connection.ex, lib/tortoise/connection/receiver.ex, lib/tortoise/connection/transmitter.ex, lib/tortoise/pipe.ex, lib/tortoise/transport.ex, lib/tortoise/transport/ssl.ex, lib/tortoise/transport/tcp.ex, mix.exs, mix.lock, test/support/scripted_mqtt_server.exs, test/support/test_tcp_tunnel.exs, test/test_helper.exs, test/tortoise/connection/controller_test.exs, test/tortoise/connection/receiver_test.exs, test/tortoise/connection/transmitter_test.exs, test/tortoise/connection_test.exs, test/tortoise/pipe_test.exs
Make it possible to connect to a broker using alternative transport forms, such as ssl. To achieve this I have looked into Ranch, which does this, and will implement an abstraction aiming to normalise the interface found in the `:gen_tcp` and `:ssl` modules.
When applied this should fix #3
=> Support multiple transport forms

CHANGELOG.md, README.md, lib/tortoise/connection/receiver.ex, mix.exs, test/tortoise/connection/receiver_test.exs
When the network connection chunked a message it would end up crashing because I had goofed up a pattern match. I have added two tests, one that triggered that issue, and one that was just one byte from triggering it (on my system, at least).
=> Fix an issue in the receiver that made it crash on larger messages

lib/tortoise/app.ex, lib/tortoise/connection.ex, lib/tortoise/connection/controller.ex, lib/tortoise/connection/inflight.ex, lib/tortoise/connection/receiver.ex, lib/tortoise/connection/transmitter.ex, lib/tortoise/registry.ex, test/tortoise/connection/receiver_test.exs
This PR gathers boilerplate from the different processes which collaborate through the registry, and puts it in a central Registry module.
=> Add dedicated Registry module

coveralls.json, lib/tortoise.ex, lib/tortoise/connection.ex, lib/tortoise/connection/controller.ex, lib/tortoise/handler.ex, test/tortoise/connection/controller_test.exs, test/tortoise/connection_test.exs, test/tortoise/handler_test.exs
When implementing a callback in the gen_statem-module, some of the callbacks accept a list of next actions. In gen_statem this allow interim states to be visited, or replying back to a caller, or stopping.
In the Tortoise.Handler the `{:ok, new_state}` given to most of the callbacks could be extended to accept `{:ok, new_state, next_actions}` where `next_actions` is a list of actions the controller should act out in the order they are defined. Actions could be:
- `{:subscribe, topic_filter, qos: n}`
- `{:unsubscribe, topic_filter}`
- <strike>`{:publish, topic, payload, opts}`</strike> (will not get implemented)
Of course these actions could lead to eternal loops, but that is part of the deal. This will be set in place to give the user a way to do things "right" as all the operations will …
=> gen_statem style callbacks for the user defined handler module

CHANGELOG.md, lib/tortoise/connection.ex, lib/tortoise/connection/backoff.ex, lib/tortoise/connection/supervisor.ex, mix.exs, test/support/scripted_transport.exs, test/test_helper.exs, test/tortoise/connection/backoff_test.exs, test/tortoise/connection_test.exs
This pull-request aim to improve situations where the client cannot get a connection to the broker—as #46 highlight: there is no retry when the client fail its initial connect.
The solution to this is to implement an incremental backoff, and retry the connection in the case the network should become available, the configuration on the broker should change, or something third that will allow us to make the connection.
I consider making some "blame management" on the connection failure reason. There could be situations where it would never be able to reconnect. Perhaps I should consider just killing the connection if the broker refute it, the password/user is unknown, etc.
If applied this should take care of:
- Fix #44 Implement incremental backoff when trying to reconnect to broker
- Fix …
=> Reconnection retries

CHANGELOG.md, README.md, lib/tortoise/connection.ex, mix.exs, test/support/scripted_transport.exs, test/tortoise/connection_test.exs
This implement the behavior observed from a client connected to a VerneMQ server that is being rebooted.
First it will close the connection, then it will reply with `{:error, :econnrefused}` a couple of times; and then it will finally accept connections again.
=> Handle a rebooting broker

CHANGELOG.md, README.md, lib/tortoise/connection/receiver.ex, mix.exs, test/tortoise/connection/receiver_test.exs
An error has been reported where Tortoise could report a protocol violation because of an invalid header length when receiving data from a slow connection. When digging into this issue it seems the be caused by the fixed_header parser in the receiver module that had a pattern match that would report a faulty header length when it received a partial header. The problem occurred because the MQTT broker in question send one byte at a time.
This PR will ensure we only report a invalid header length when we receive more than 40 bits of header information, and haven't found a header yet.
=> Make sure the invalid header length is anything above 5 bytes

CHANGELOG.md, lib/tortoise/connection/controller.ex, test/tortoise/connection/controller_test.exs
If an unexpected message is received from the server the controller will stop with the reason `{:protocol_violation, {:unexpected_package_from_remote, package}}` where package is the unexpected package. The implementer can then log it or do whatever.
=> Error when the server send unexpected messages

CHANGELOG.md, lib/tortoise/connection.ex, lib/tortoise/connection/controller.ex, lib/tortoise/events.ex, test/tortoise/connection/controller_test.exs
Allow processes to listen in on `:status` and get a message when the connection status changes. When registered for status-messages a process will receive a message of the form: 
- `{{Tortoise, client_id}, :status, :up}` when the client has a connection to the broker
- `{{Tortoise, client_id}, :status, :down}` when it drop the connection.
A process can register this status message via the `Tortoise.Events` pubsub like this `Tortoise.Events.register(client_id, :status)`.
=> Expose connection status changes through the Tortoise.Events pubsub

CHANGELOG.md, lib/tortoise/connection.ex, lib/tortoise/connection/receiver.ex, test/tortoise/connection/controller_test.exs
By dispatching that the status is down via the pubsub, the receiver can inform the connection that it should reconnect; also we can eventually have the inflight process roll back its state and resend the messages when it has a connection.
=> Use the pubsub to communicate when the receiver drop the connection

CHANGELOG.md, lib/tortoise/transport/ssl.ex
This will allow the user to pass in a binary as the host name, in which case it will get coerced into a charlist.
Fixes #66
=> Coerce the host given to the SSL transport to a charlist

CHANGELOG.md, lib/tortoise/package/subscribe.ex, lib/tortoise/package/unsubscribe.ex, test/test_helper.exs, test/tortoise/package/subscribe_test.exs
Updated the unsubscribe package test generator to not generate empty subscription packages as well.
If applied this should fix #69
=> A valid unsubscribe package must contain at least one topic filter

CHANGELOG.md, lib/tortoise/package/disconnect.ex, lib/tortoise/package/pingreq.ex, lib/tortoise/package/pingresp.ex, lib/tortoise/package/puback.ex, lib/tortoise/package/pubcomp.ex, lib/tortoise/package/pubrec.ex, lib/tortoise/package/pubrel.ex, lib/tortoise/package/unsuback.ex, lib/tortoise/registry.ex, mix.exs, mix.lock
I've upgraded to the latest (release candidate) release of dialixer—and I have added the following to the configuration `flags: [:error_handling, :race_conditions, :underspecs]`
The current warnings has been taken care of.
=> Make the project pass dialyzer

README.md, mix.exs
Since QuickCheck is only used in "test" environment, would you consider restricting `eqc_ex` in the environment only?
=>  Make "eqc_ex" dependency only available in test

lib/tortoise/connection.ex, test/tortoise/connection_test.exs
I was receiving TLS certificate unknown alerts from the server. They were handled differently from other connection errors. I wasn't completely sure if you wanted to handle errors on a case-by-case basis to see if they could benefit from more information or not. The only other error that I've seen so far is `{:error, {:tls_alert, something}}` if that's the case.
=> Catch other connection errors

lib/tortoise/connection.ex
Use the connection backoff when there's a timeout during connection
=> Classify connection timeout as connectivity error

docs/connecting_to_a_mqtt_broker.md
Passing just a DER encoded key to Tortoise.Transport.SSL made the
connection fail, clarify it in the docs.
=> docs: clarify the correct format of SSL key option

lib/tortoise.ex
When publishing, one should be able to set a timeout on establishing the connection so that the timeout does not default to :infinity 
I've been experiencing intermittent "lock ups" of a genserver client of Tortoise. I could not identify the precise cause but this PR would remove a potential cause.
=> Allow setting publish connection timeouts

lib/tortoise/transport/ssl.ex, lib/tortoise/transport/tcp.ex
This adds support for passing through options to the underlying Transport
constructors, for example to support IPv6. Patch originally suggested by Brian
May.
Fixes #111.
Suggested-by: Brian May <brian@linuxpenguins.xyz>
Signed-off-by: Toke Høiland-Jørgensen <toke@toke.dk>
=> Support passing options to Transport constructors

lib/tortoise/connection.ex
This is similar to what done in #94, and is necessary so that `Tortoise.Connection` will attempt a reconnection instead of terminating when the network is temporarily unreachable.
In my IoT project, if I unplug the ethernet cable, the following happens:
1. Upon the next keepalive ping, the `Tortoise.Connection` GenServer terminates due to `:ping_timeout`. Ideally, this would not cause the server to terminate, but rather to attempt a re-connection (as suggested in #116), but this is not the focus of this PR.
2. As the `Tortoise.Connection` GenServer is restarted by its supervisor, it quickly and repeatedly crashes when trying to connect due to `{:error, :enetunreach}`, and eventually the supervisor stops trying to restart it and the whole application terminates.
This PR classifies such …
=> Classify :enetunreach as connectivity error

lib/tortoise/connection.ex
Dialyzer was giving errors when calling the function and passing the
server option
=> Add server option to Connection.start_link/1 spec

CHANGELOG.md, docs/connecting_to_a_mqtt_broker.md, lib/tortoise/connection.ex, lib/tortoise/handler.ex
We have a need to set a different last will message for each connection to the MQTT server. I added a handler callback to get a last will message on each connect. If none is provided by the handler, the (now default) last will message, set when init-ing the Connection genserver, is used. This is meant to be a non-breaking, backward-compatible change.
=> Get last will message from handler on connecting
